{
 "title": "Monitor Page",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Default Views", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reports per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n   $__timeGroup(reference_time::timestamp,'1m') as time,\n  count(report_items) as value,\n  agent_endpoint_uri AS metric\nFROM vw_ari_rpt_set join registered_agents on vw_ari_rpt_set.agent_id = registered_agents.registered_agents_id\ngroup by 1, agent_endpoint_uri\norder by time asc"
    }
   ]
  },
  {
   "title": "Agents",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n *\nFROM registered_agents"
    }
   ]
  },
  {
   "title": "Received Reports",
   "type": "table",
   "description": "table for displaying all received reports ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "columns": [
      { "selector": "agent_time", "text": "", "type": "string" },
      { "selector": "agent_id", "text": "", "type": "string" },
      { "selector": "nonce_cbor", "text": "", "type": "string" },
      { "selector": "report_source", "text": "", "type": "string" },
      { "selector": "report_items", "text": "", "type": "string" }
     ],
     "pagination_mode": "none",
     "pagination_param_page_field_name": "page",
     "pagination_param_page_field_type": "body_data",
     "pagination_param_page_value": 1,
     "pagination_param_size_field_name": "size",
     "pagination_param_size_field_type": "body_data",
     "pagination_param_size_value": 5,
     "parser": "backend",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "report/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "ARIs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n*\nFROM vw_obj_metadata\n"
    }
   ]
  },
  {
   "title": "ari://ietf/dtnma-agent/CTRL/inspect(//ietf/dtnma-agent/EDD/num-msg-rx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$map(reports, function($v) {\n  $v.nestedArray.{\n    \"value\": \"col 0\"\n  }\n})\n",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\n| mv-expand \"reports\"\n| mv-expand \"reports\"\n| extend \"reference_time\"=todatetime(\"reports.reference_time\")\n| extend \"num_msg_rx\"=\"reports.col 0\"\n| extend \"parts\"=split(\"num_msg_rx\",'/')\n| extend \"parts\"=\"parts[2]\"\n| extend \"num_msg_rx\"=toint(\"parts\") \n| extend \"time\"=\"reference_time\"\n| extend \"value\"=\"num_msg_rx\"\n| extend \"metric\"=\"agent\"\n| project   \"time\", \"value\", \"agent\"\n\n\n\n\n\n",
     "url": "report/dictionary/search/eid/",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"agent_eids\": [\n    \"ipn:2.6\",\"ipn:3.6\"\n  ],\n  \"source_cbors\": [\n    \"8564696574666b64746e6d612d6167656e742267696e7370656374818464696574666b64746e6d612d6167656e74236a6e756d2d6d73672d7278\"\n  ]\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Hello_rpt_agent_dictionary_search",
   "type": "table",
   "description": "Using `report/dictionary/search/eid/` to display `hello` reports",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\n| mv-expand \"reports\"\n| mv-expand \"reports\"\n| extend \"agent_time\"=\"reports.agent_time\"\n| extend \"sw-vendor\"=\"reports.sw-vendor\"\n| extend \"sw-version\"=\"reports.sw-version\"\n| extend \"capability\"=\"reports.capability\"\n| project \"agent\", \"agent_time\", \"sw-vendor\", \"sw-version\", \"capability\"\n\n",
     "url": "report/dictionary/search/eid/",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"agent_eids\": [\n    \"ipn:3.6\", \"ipn:2.6\"\n  ],\n  \"source_cbors\": [\n    \"8401012100\",\n    \"8464696574666b64746e6d612d6167656e74216568656c6c6f\"\n  ]\n}",
      "headers": [],
      "method": "POST",
      "params": []
     }
    }
   ]
  },
  {
   "title": "User Created",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "New panel",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      { "dataset": "amp_core" }
     ]
    }
   ]
  }
 ]
}