##
## Copyright (c) 2023 The Johns Hopkins University Applied Physics
## Laboratory LLC.
##
## This file is part of the Asynchronous Network Management System (ANMS).
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##     http://www.apache.org/licenses/LICENSE-2.0
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## This work was performed for the Jet Propulsion Laboratory, California
## Institute of Technology, sponsored by the United States Government under
## the prime contract 80NM0018D0004 between the Caltech and NASA under
## subcontract 1658085.
##
version: '3.9'

services:
  db:
    image: mysql
    volumes:
      - ${PWD}:/shared
      - ${PWD}/Database_Scripts/Tables/amp_core_create_database.sql:/docker-entrypoint-initdb.d/00-amp_core_create_database.sql
      - ${PWD}/Database_Scripts/Tables/transcoder.sql:/docker-entrypoint-initdb.d/00-transcoder.sql
      - ${PWD}/Database_Scripts/Views/obj_view.sql:/docker-entrypoint-initdb.d/01-obj_view.sql
      - ${PWD}/Database_Scripts/Views/ari_view.sql:/docker-entrypoint-initdb.d/14-ari_view.sql
      - ${PWD}/Database_Scripts/Views/ctrl_view.sql:/docker-entrypoint-initdb.d/04-ctrl_view.sql
      - ${PWD}/Database_Scripts/Views/edd_view.sql:/docker-entrypoint-initdb.d/05-edd_view.sql
      - ${PWD}/Database_Scripts/Views/mac_view.sql:/docker-entrypoint-initdb.d/06-mac_view.sql
      - ${PWD}/Database_Scripts/Views/oper_view.sql:/docker-entrypoint-initdb.d/07-oper_view.sql
      - ${PWD}/Database_Scripts/Views/message_view.sql:/docker-entrypoint-initdb.d/08-message_view.sql
      - ${PWD}/Database_Scripts/Views/rpt_view.sql:/docker-entrypoint-initdb.d/13-rpt_view.sql
      - ${PWD}/Database_Scripts/Views/sbr_view.sql:/docker-entrypoint-initdb.d/09-sbr_view.sql
      - ${PWD}/Database_Scripts/Views/tbr_view.sql:/docker-entrypoint-initdb.d/10-tbr_view.sql
      - ${PWD}/Database_Scripts/Views/tblt_view.sql:/docker-entrypoint-initdb.d/11-tblt_view.sql
      - ${PWD}/Database_Scripts/Views/tnvc_view.sql:/docker-entrypoint-initdb.d/12-tnvc_view.sql
      - ${PWD}/Database_Scripts/Views/parm_view.sql:/docker-entrypoint-initdb.d/13-parm_view.sql
      - ${PWD}/Database_Scripts/Views/var_view.sql:/docker-entrypoint-initdb.d/13-var_view.sql
      - ${PWD}/Database_Scripts/Routines/all_routines.sql:/docker-entrypoint-initdb.d/16-all_routines.sql
      - ${PWD}/Agent_Scripts/adm_amp_agent.sql:/docker-entrypoint-initdb.d/30-adm_amp_agent.sql
      - ${PWD}/Agent_Scripts/adm_bp_agent.sql:/docker-entrypoint-initdb.d/30-adm_bp_agent.sql
      - ${PWD}/Agent_Scripts/adm_ltp_agent.sql:/docker-entrypoint-initdb.d/30-adm_ltp_agent.sql
      - ${PWD}/Agent_Scripts/adm_ionsec_admin.sql:/docker-entrypoint-initdb.d/30-adm_ionsec_admin.sql
      - ${PWD}/Agent_Scripts/adm_ion_ltp_admin.sql:/docker-entrypoint-initdb.d/30-adm_ion_ltp_admin.sql
      - ${PWD}/Agent_Scripts/adm_ion_ipn_admin.sql:/docker-entrypoint-initdb.d/30-adm_ion_ipn_admin.sql
      - ${PWD}/Agent_Scripts/adm_ion_bp_admin.sql:/docker-entrypoint-initdb.d/30-adm_ion_bp_admin.sql
      - ${PWD}/Agent_Scripts/adm_ion_admin.sql:/docker-entrypoint-initdb.d/30-adm_ion_admin.sql
      - ${PWD}/Agent_Scripts/adm_sbsp.sql:/docker-entrypoint-initdb.d/30-adm_sbsp.sql
      - ${PWD}/Database_Scripts/Tables/healthcheck_roles.sql:/docker-entrypoint-initdb.d/17-healthcheck_roles.sql
      - ${PWD}/Database_Scripts/amp_core_functions.sql:/docker-entrypoint-initdb.d/17-amp_core_functions.sql

      # Optional: Specify a folder for reliably persistent storage, omit and use force-recreate to guarantee fresh starts, or
      # manually delete prior to start
      - ${PWD}/tmp/mysql:/var/lib/mysql
    restart: always
    # MySQL8 Authentication fix (https://github.com/docker-library/mysql/issues/454) -- quicker than figuring out how to install plugin
    command: --lower_case_table_names=1 --default-authentication-plugin=mysql_native_password
    hostname: amp_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: amp_core
      MYSQL_USER: amp
      MYSQL_PASSWORD: amp
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080