--
-- Copyright (c) 2023 The Johns Hopkins University Applied Physics
-- Laboratory LLC.
--
-- This file is part of the Asynchronous Network Management System (ANMS).
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--     http://www.apache.org/licenses/LICENSE-2.0
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- This work was performed for the Jet Propulsion Laboratory, California
-- Institute of Technology, sponsored by the United States Government under
-- the prime contract 80NM0018D0004 between the Caltech and NASA under
-- subcontract 1658085.
--

-- INSERT INTO registered_agents(registered_agents_id, agent_id_string) VALUES(0, 'Agent 0');
-- INSERT INTO registered_agents(registered_agents_id, agent_id_string) VALUES(1, 'Agent 1');
-- INSERT INTO registered_agents(registered_agents_id, agent_id_string) VALUES(2, 'Agent 2');
--
-- INSERT INTO message_group(group_id, ts, is_outgoing, state_id) VALUES(0, 0, false, 0);
-- INSERT INTO message_group(group_id, ts, is_outgoing, state_id) VALUES(1, 0, false, 1);
-- INSERT INTO message_group(group_id, ts, is_outgoing, state_id) VALUES(2, 0, false, 2);
--
-- INSERT INTO message_group_entry(group_id, ack, nak, acl, order_num, type_id) VALUES(0, true, false, true, 0, 0);
-- INSERT INTO message_group_entry(group_id, ack, nak, acl, order_num, type_id) VALUES(1, false, false, true, 1, 1);
-- INSERT INTO message_group_entry(group_id, ack, nak, acl, order_num, type_id) VALUES(2, true, true, true, 2, 2);
-- INSERT INTO message_group_entry(group_id, ack, nak, acl, order_num, type_id) VALUES(1, true, true, true, 2, 2);
--
-- INSERT INTO alert(title, status, message) VALUES('Alert 0', 0, 'Alert 0 Message');
-- INSERT INTO alert(title, status, message) VALUES('Alert 1', 1, 'Alert 1 Message');
-- INSERT INTO alert(title, status, message) VALUES('Alert 2', 2, 'Alert 2 Message');
--
-- INSERT INTO message_agents(message_id, agent_id) VALUES(1,0);
-- INSERT INTO message_agents(message_id, agent_id) VALUES(2,1);
-- INSERT INTO message_agents(message_id, agent_id) VALUES(3,2);
-- INSERT INTO message_agents(message_id, agent_id) VALUES(4,2);

INSERT INTO "user" (id, username, email, first_name, last_name, password, is_enabled, roles, permissions) VALUES(0, 'admin', 'admin@admin.com', 'Admin', 'User', '$2b$12$S5hnlzHa9n.2St0WrJCNf.wiNYRCY/iA7SRQvkmDG8DNql6Uo3VT2', true, ARRAY[0], ARRAY[0]);
