SERVER_HOST: SERVER_HOST_TEMPLATE 
SERVER_PORT: SERVER_PORT_TEMPLATE 
SERVER_CHROOT: SERVER_CHROOT_TEMPLATE 
SERVER_API_CHROOT: SERVER_API_CHROOT_TEMPLATE 
SERVER_BIND: SERVER_BIND_TEMPLATE 
SERVER_BEHIND_PROXY: SERVER_BEHIND_PROXY_TEMPLATE 

# SSL
SERVER_SSL: SERVER_SSL_TEMPLATE 
SERVER_SSL_CRT: SERVER_SSL_CRT_TEMPLATE 
SERVER_SSL_KEY: SERVER_SSL_KEY_TEMPLATE 
SERVER_SSL_PWD: SERVER_SSL_PWD_TEMPLATE 
SERVER_PROXY_SSL: SERVER_PROXY_SSL_TEMPLATE 

# Gunicorn
SERVER_WORKERS: SERVER_WORKERS_TEMPLATE 
SERVER_TIMEOUT: SERVER_TIMEOUT_TEMPLATE 

# Scheduler
APSCHEDULER_MAX_THREAD_WORKERS: APSCHEDULER_MAX_THREAD_WORKERS_TEMPLATE 
APSCHEDULER_MAX_PROCESS_WORKERS: APSCHEDULER_MAX_PROCESS_WORKERS_TEMPLATE 

# ASGI App Settings
APP_TITLE: APP_TITLE_TEMPLATE 
APP_VERSION: APP_VERSION_TEMPLATE 
APP_STATIC_DIR: APP_STATIC_DIR_TEMPLATE 
APP_TEMPLATES_DIR: APP_TEMPLATES_DIR_TEMPLATE 
APP_SECRET_KEY: APP_SECRET_KEY_TEMPLATE 
APP_CSRF_ENABLED: APP_CSRF_ENABLED_TEMPLATE 
APP_JWT_ALGORITHM: APP_JWT_ALGORITHM_TEMPLATE 
APP_ALLOW_INITIAL_USER: APP_ALLOW_INITIAL_USER_TEMPLATE 
APP_INITIAL_USER_NAME: APP_INITIAL_USER_NAME_TEMPLATE 
APP_INITIAL_FIRST_NAME: APP_INITIAL_FIRST_NAME_TEMPLATE 
APP_INITIAL_LAST_NAME: APP_INITIAL_LAST_NAME_TEMPLATE 
APP_INITIAL_PASSWORD: APP_INITIAL_PASSWORD_TEMPLATE 
APP_INITIAL_USER_EMAIL: APP_INITIAL_USER_EMAIL_TEMPLATE 
APP_PASSWORD_COMPLEXITY_LEN: APP_PASSWORD_COMPLEXITY_LEN_TEMPLATE 

# ASGI App Cookie Settings
APP_SESSION_COOKIE_NAME: APP_SESSION_COOKIE_NAME_TEMPLATE 
APP_SESSION_COOKIE_LIFETIME: APP_SESSION_COOKIE_LIFETIME_TEMPLATE 
APP_SESSION_COOKIE_SECURE: APP_SESSION_COOKIE_SECURE_TEMPLATE 
APP_SESSION_COOKIE_HTTPONLY: APP_SESSION_COOKIE_HTTPONLY_TEMPLATE 
APP_SESSION_REFRESH_EACH_REQUEST: APP_SESSION_REFRESH_EACH_REQUEST_TEMPLATE 
APP_SESSION_COOKIE_SAMESITE: APP_SESSION_COOKIE_SAMESITE_TEMPLATE 
APP_SESSION_TOKEN_LIFETIME: APP_SESSION_TOKEN_LIFETIME_TEMPLATE 
# KeyCloak Settings (Delegates all auth to external server...)
APP_OPENID_KEYCLOAK_ENABLED: APP_OPENID_KEYCLOAK_ENABLED_TEMPLATE 
APP_OPENID_KEYCLOAK_CLIENT_NAME: APP_OPENID_KEYCLOAK_CLIENT_NAME_TEMPLATE 
APP_OPENID_KEYCLOAK_CLIENT_ID: APP_OPENID_KEYCLOAK_CLIENT_ID_TEMPLATE 
APP_OPENID_KEYCLOAK_CLIENT_SECRET: APP_OPENID_KEYCLOAK_CLIENT_SECRET_TEMPLATE 
APP_OPENID_KEYCLOAK_HOST: APP_OPENID_KEYCLOAK_HOST_TEMPLATE 
APP_OPENID_KEYCLOAK_REALM: APP_OPENID_KEYCLOAK_REALM_TEMPLATE 
APP_OPENID_KEYCLOAK_CONFIG_URL: APP_OPENID_KEYCLOAK_CONFIG_URL_TEMPLATE 
APP_OPENID_KEYCLOAK_AUTH_URL: APP_OPENID_KEYCLOAK_AUTH_URL_TEMPLATE 
APP_OPENID_KEYCLOAK_TOKEN_URL: APP_OPENID_KEYCLOAK_TOKEN_URL_TEMPLATE 

# Relation DB Settings
DB_SCHEME: DB_SCHEME_TEMPLATE 
DB_ASYNC_SCHEME: DB_ASYNC_SCHEME_TEMPLATE 
DB_HOST: DB_HOST_TEMPLATE 
DB_PORT: DB_PORT_TEMPLATE 
DB_USER: DB_USER_TEMPLATE 
DB_PASS: DB_PASS_TEMPLATE 
DB_CHROOT: DB_CHROOT_TEMPLATE 


# mqtt Settings
# Let the name resolver determine the host to use at runtime
MQTT_HOST: MQTT_HOST_TEMPLATE 
MQTT_PORT: MQTT_PORT_TEMPLATE 
MQTT_PASS: MQTT_PASS_TEMPLATE 
MQTT_USER: MQTT_USER_TEMPLATE 

# nm Settings
NM_HOST: NM_HOST_TEMPLATE 
NM_PORT: NM_PORT_TEMPLATE 
NM_API_BASE: NM_API_BASE_TEMPLATE 

DB_PARAMS: DB_PARAMS_TEMPLATE 
DB_MODELS_DIR: DB_MODELS_DIR_TEMPLATE 
# https://docs.sqlalchemy.org/en/latest/core/engines.html
DB_POOL_SIZE: DB_POOL_SIZE_TEMPLATE 
DB_POOL_TIMEOUT: DB_POOL_TIMEOUT_TEMPLATE 
DB_POOL_RECYCLE: DB_POOL_RECYCLE_TEMPLATE 
DB_MAX_OVERFLOW: DB_MAX_OVERFLOW_TEMPLATE 
DB_ECHO: DB_ECHO_TEMPLATE 
DB_ENCODING: DB_ENCODING_TEMPLATE 

OPENSEARCH_HOST: OPENSEARCH_HOST_TEMPLATE 
OPENSEARCH_PORT: OPENSEARCH_PORT_TEMPLATE 
OPENSEARCH_AUTH_USERNAME: OPENSEARCH_AUTH_USERNAME_TEMPLATE 
OPENSEARCH_AUTH_PASSWORD: OPENSEARCH_AUTH_PASSWORD_TEMPLATE 
OPENSEARCH_USE_SSL: OPENSEARCH_USE_SSL_TEMPLATE 
OPENSEARCH_VERIFY_CERTS: OPENSEARCH_VERIFY_CERTS_TEMPLATE 
OPENSEARCH_ASSERT_HOSTNAME: OPENSEARCH_ASSERT_HOSTNAME_TEMPLATE 
OPENSEARCH_SHOW_WARN: OPENSEARCH_SHOW_WARN_TEMPLATE 
OPENSEARCH_INDEX_NAME: OPENSEARCH_INDEX_NAME_TEMPLATE 
OPENSEARCH_INDEX_BODY: OPENSEARCH_INDEX_BODY_TEMPLATE 

# Email Settings
SMTP_TLS: SMTP_TLS_TEMPLATE 
SMTP_PORT: SMTP_PORT_TEMPLATE 
SMTP_HOST: SMTP_HOST_TEMPLATE 
SMTP_USER: SMTP_USER_TEMPLATE 
SMTP_PASS: SMTP_PASS_TEMPLATE 
EMAIL_ENABLED: EMAIL_ENABLED_TEMPLATE 
EMAIL_FROM_NAME: EMAIL_FROM_NAME_TEMPLATE 
EMAIL_FROM_EMAIL: EMAIL_FROM_EMAIL_TEMPLATE 
EMAIL_TEMPLATES_DIR: EMAIL_TEMPLATES_DIR_TEMPLATE 
EMAIL_RESET_TOKEN_EXPIRE_LIFETIME: EMAIL_RESET_TOKEN_EXPIRE_LIFETIME_TEMPLATE 