#!/usr/bin/bash

PROXY_CONFIG=/etc/httpd/site.conf.d/anms_proxy.conf

if [ -z "$PROXY_URLS" ]; then
  echo "ERROR: PROXY_URLS is missing."
  exit 1
fi
echo "# This file was autogenerated by run_proxy.sh using env variable PROXY_URLS=${PROXY_URLS}" > $PROXY_CONFIG

echo "" >> $PROXY_CONFIG
for url in $PROXY_URLS; do
  if echo "$url" | grep -q ','; then
    # Used to redirect when the endpoint does not match the destination path
    endpoint=$(echo "$url" | cut -d, -f1)
    url=$(echo "$url" | cut -d, -f2)
  else
    endpoint=$(echo "$url" | cut -d/ -f4-)
    # ensures the slashes are consistent
    url="$(echo "$url" | cut -d/ -f1-3)/${endpoint}"
  fi
  echo "ProxyPass /$endpoint $url" >> $PROXY_CONFIG
  echo "ProxyPassReverse /$endpoint $url" >> $PROXY_CONFIG
done

# Start httpd
echo "Start httpd"
/usr/sbin/httpd -D FOREGROUND # DEBUG - enable this line
# for debugging httpd if it exits
#while true; do sleep 1000; done
