#!/usr/bin/env bash

PROXY_CONFIG=/etc/httpd/site.conf.d/anms_proxy.conf

if [ -z "$PROXY_URLS" ]; then
  echo "ERROR: PROXY_URLS is missing."
  exit 1
fi
echo "# This file was autogenerated by run_proxy.sh using env variable PROXY_URLS=${PROXY_URLS}" > $PROXY_CONFIG

# Collect proxy rules and redirect-rewrite rules.
# Apache ProxyPass is first-match, so longer/more-specific paths must come first.
declare -a ENDPOINTS=()
declare -a URLs=()
declare -a REWRITE_BACKEND=()  # backend paths that may appear in redirect Location headers
declare -a REWRITE_FRONTEND=() # frontend paths to rewrite them to

echo "" >> $PROXY_CONFIG
for url in $PROXY_URLS; do
  if echo "$url" | grep -q ','; then
    endpoint=$(echo "$url" | cut -d, -f1)
    url=$(echo "$url" | cut -d, -f2)
    backend_path=$(echo "$url" | cut -d/ -f4-)
    # If the endpoint differs from the backend path, track a redirect rewrite rule.
    # E.g., core/docs -> http://anms-core:5555/docs: when anms-core redirects /docs -> /docs/,
    # rewrite the Location header to /core/docs/ so the browser stays under /core/.
    if [ -n "$backend_path" ] && [ "$endpoint" != "$backend_path" ]; then
      REWRITE_BACKEND+=("/$backend_path")
      REWRITE_FRONTEND+=("/$endpoint")
    fi
  else
    endpoint=$(echo "$url" | cut -d/ -f4-)
    # ensures the slashes are consistent
    url="$(echo "$url" | cut -d/ -f1-3)/${endpoint}"
  fi
  ENDPOINTS+=("/$endpoint")
  URLs+=("$url")
done

# Add Location header rewrite rules for backend redirects
# These rewrite e.g. "Location: /docs/" -> "Location: /core/docs/" in proxied responses
if [ ${#REWRITE_BACKEND[@]} -gt 0 ]; then
  echo "# Rewrite backend redirect Location headers to frontend paths" >> $PROXY_CONFIG
  for i in "${!REWRITE_BACKEND[@]}"; do
    echo "Header edit Location \"${REWRITE_BACKEND[$i]}\" \"${REWRITE_FRONTEND[$i]}\"" >> $PROXY_CONFIG
  done
fi

# Sort proxy rules by endpoint length descending (more-specific first)
indices=(
  $(for i in "${!ENDPOINTS[@]}"; do
    echo "$i ${#ENDPOINTS[$i]}"
  done | sort -k2 -rn -k1 -n | awk '{print $1}')
)

for i in "${indices[@]}"; do
  echo "ProxyPass ${ENDPOINTS[$i]} ${URLs[$i]}" >> $PROXY_CONFIG
  echo "ProxyPassReverse ${ENDPOINTS[$i]} ${URLs[$i]}" >> $PROXY_CONFIG
done

# Start httpd
echo "Start httpd"
/usr/sbin/httpd -D FOREGROUND # DEBUG - enable this line
# for debugging httpd if it exits
#while true; do sleep 1000; done
