#!/usr/bin/env bash

PROXY_CONFIG=/etc/httpd/site.conf.d/anms_proxy.conf

if [[ -z "$PROXY_URLS" ]]; then
  echo "ERROR: PROXY_URLS is missing."
  exit 1
fi
echo "# This file was autogenerated by run_proxy.sh using env variable PROXY_URLS=${PROXY_URLS}" > $PROXY_CONFIG

# Collect proxy rules. Apache ProxyPass is first-match, so longer/more-specific paths must come first.
declare -a ENDPOINTS=()
declare -a URLs=()

echo "" >> $PROXY_CONFIG
for url in $PROXY_URLS; do
  if echo "$url" | grep -q ','; then
    endpoint=$(echo "$url" | cut -d, -f1)
    url=$(echo "$url" | cut -d, -f2)
  else
    endpoint=$(echo "$url" | cut -d/ -f4-)
    # ensures the slashes are consistent
    url="$(echo "$url" | cut -d/ -f1-3)/${endpoint}"
  fi
  ENDPOINTS+=("/$endpoint")
  URLs+=("$url")
done

# Sort proxy rules by endpoint length descending (more-specific first)
indices=(
  $(for i in "${!ENDPOINTS[@]}"; do
    echo "$i ${#ENDPOINTS[$i]}"
  done | sort -k2 -rn -k1 -n | awk '{print $1}')
)

for i in "${indices[@]}"; do
  echo "ProxyPass ${ENDPOINTS[$i]} ${URLs[$i]}" >> $PROXY_CONFIG
  echo "ProxyPassReverse ${ENDPOINTS[$i]} ${URLs[$i]}" >> $PROXY_CONFIG
done

# Start httpd
echo "Start httpd"
/usr/sbin/httpd -D FOREGROUND # DEBUG - enable this line
# for debugging httpd if it exits
#while true; do sleep 1000; done
