name: Test anms-core
on:
  push:
    paths:
      - .github/workflows/anms-core.yaml
      - deps/**
      - anms-core/**

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip3 install deps/anms-ace
          pip3 install deps/anms-camp
      - name: Install
        working-directory: anms-core
        run: pip3 install -e '.[test]'
      - name: Run test
        working-directory: anms-core
        run: PYTHONPATH=src python3 -m pytest --junit-xml=testresults.xml --cov=anms test

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip3 install deps/anms-ace
          pip3 install deps/anms-camp
      - name: Install flake8
        working-directory: anms-core
        run: pip3 install -e '.[flake8]'
      - name: Run flake8
        working-directory: anms-core
        run: |
          FAIL_SRC=0
          flake8 src || FAIL_SRC=$?
