name: Test anms-core
on:
  push:
    paths:
      - .github/workflows/anms-core.yaml
      - deps/**
      - anms-core/**

jobs:
  flake8:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip3 install deps/dtnma-ace
          pip3 install deps/dtnma-camp
      - name: Install flake8
        working-directory: anms-core
        run: pip3 install -e '.[flake8]'
      - name: Run flake8
        working-directory: anms-core
        run: |
          FAIL_SRC=0
          flake8 src || FAIL_SRC=$?
  anms-core_integration-test:
    runs-on: ubuntu-24.04
    env:
      ANMS_COMPOSE_OPTS: -f docker-compose.yml --profile light
      TEST_COMPOSE_OPTS: -f anms-core/integration_test/docker-compose.yml
      HOST_SOCKDIR: sockdir
      CTR_SOCKDIR: /var/tmp/nm
      DOCKER_CMD: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build ANMS
        run: docker compose ${ANMS_COMPOSE_OPTS} build
      - name: build
        run:
          docker compose ${TEST_COMPOSE_OPTS} build
      - name: Build Volume
        run: |
          ./create_volume.sh ./puppet/modules/apl_test/files/anms/tls
          sudo mkdir /run/anms
      - name: run
        run: |
          docker compose  ${ANMS_COMPOSE_OPTS} up -d 
          docker compose ${TEST_COMPOSE_OPTS} run test-fixture
      - name: after_script
        run: |
          if [ "${CI_JOB_STATUS}" = 'failed' ]; then
            docker logs anms-core
          fi

