name: Test aricodec
on:
  push:
    paths:
      - .github/workflows/aricodec.yaml
      - deps/**
      - aricodec/**

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip3 install deps/dtnma-ace
      - name: Install flake8
        working-directory: aricodec
        run: pip3 install -e '.[flake8]'
      - name: Run flake8
        working-directory: aricodec
        run: |
          FAIL_SRC=0
          flake8 src || FAIL_SRC=$?
