# On merge to main publish with the 'latest' label
# Publish with release label when a releaes is published.
name: Build and publish containers
on:
  push:
    branches:
    - main
    # For testing: delete this prior to merging PR
    - feature/177-ghcr_container_publishing
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}/anms/

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "DOCKER_IMAGE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "DOCKER_IMAGE_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push images via compose
        run: |
          export DOCKER_IMAGE_PREFIX=${{ env.DOCKER_IMAGE_PREFIX }}
          export DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}
          # bake integrates buildx with compose
          docker compose bake --push \
            --set "*.platform=linux/amd64,linux/arm64"
