name: Puppet module
on:
  push:
    branches:
    - main
  pull_request: {} # any target
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  prep:
    name: Download modules
    runs-on: ubuntu-24.04
    container: quay.io/centos/centos:stream9
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Install dependencies
        run: |
          dnf install -y https://yum.puppet.com/puppet7-release-el-9.noarch.rpm
          dnf install -y https://yum.puppet.com/puppet-tools-release-el-9.noarch.rpm
          dnf install -y puppet-agent-7.28.0-1.el9 puppet-bolt-3.30.0-1.el9
          update-alternatives --install /usr/bin/puppet puppet-agent /opt/puppetlabs/bin/puppet 10
          chmod +t /tmp # workaround ruby need within prep.sh
      - name: Prep project
        run: |
          ./puppet/prep.sh

  puppet-lint:
    runs-on: ubuntu-24.04
    permissions:
      contents: read # for checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.192.0
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Install puppet-lint
        run: gem install puppet-lint

      - name: Run puppet-lint
        run: puppet-lint puppet --sarif --ignore-paths 'puppet/modules/anms/files/*' > puppet-lint-results.sarif

      - name: Upload analysis results to GitHub
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: puppet-lint-results.sarif
          wait-for-processing: true
