name: Test transcoder
on:
  push:
    branches:
    - main
  pull_request: {} # any target
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  ruff:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install ruff
        working-directory: transcoder
        run: pip3 install -e '.[ruff]'
      - name: Run ruff check
        working-directory: transcoder
        run: |
          FAIL_SRC=0
          ruff check . || FAIL_SRC=$?
      - name: Run ruff format --check
        working-directory: transcoder
        run: |
          FAIL_SRC=0
          ruff format --check . || FAIL_SRC=$?
